<?php

/**
 * @file
 * thakurji theme file.
 */

/**
/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function thakurji_preprocess_node(&$variables) {
  if ($variables['node']->getType() === 'youtube_videos') {
    $field = $variables['node']->get('field_video_category');
    
    // Check if the field has a value and the entity exists
    if (!$field->isEmpty() && $field->entity) {
      $termTitle = $field->entity->label();

      // Set the view display ID based on the term title.
      $displayId = '';
      switch ($termTitle) {
        case 'Bhajan':
          $displayId = 'block_1';
          break;
        case 'Aarti':
          $displayId = 'block_2';
          break;
        case 'Katha':
          $displayId = 'block_3';
          break;
        case 'Mantra':
          $displayId = 'block_4';
          break;
        case 'Devotional movies':
          $displayId = 'block_5';
          break;
      }

      // Load and render the view
      $viewId = 'latest_video_bhajan';
      $view = \Drupal\views\Views::getView($viewId);

      if ($view && $displayId) {
        $view->setDisplay($displayId);
        $view->preExecute();
        $view->execute();

        $variables['latestVideo'] = $view->render();
      }
    }
  }
}

 function thakurji_preprocess_views_view_unformatted(&$variables) {
  foreach ($variables['rows'] as &$row) {
    if (isset($row['content']['#row']->_entity)) {
      $row['content']['#node'] = $row['content']['#row']->_entity;
    }
  }
}

function thakurji_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'homepage_festival_block' && $variables['view']->current_display === 'block_1') {
    $variables['festival_header_title_first'] = t('Year-Round');
    $variables['festival_header_title_strong'] = t('Celebrations');
    $variables['festival_header_subtitle'] = t('Experience the sacred throughout the year with our festival calendar');
  }
}


