<?php
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Ajax\AjaxResponse;
use \Drupal\Core\Ajax\HtmlCommand;
use \Drupal\Core\Ajax\RedirectCommand;
use \Drupal\Core\Mail\MailManagerInterface;
use \Drupal\Component\Utility\SafeMarkup;
use \Drupal\Component\Utility\Html;
use \Drupal\Core\Url;
use Drupal\user\UserInterface;
use \Drupal\views\ViewExecutable;
use \Drupal\views\Plugin\views\query\QueryPluginBase;
use \Drupal\Core\File;
use \Drupal\Core\File\MimeType;
use \Drupal\Core\File\MimeType\ExtensionMimeTypeGuesser;
use \Drupal\Core\File\MimeType\MimeTypeGuesser;
use \Drupal\Core\Database\Query\AlterableInterface;
use \Drupal\Core\Entity\Query\QueryInterface;


// BIG PIPE LINE CACHE ISSUE
function visitor_counter_block_build_visitor_counter_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  // Disable placeholdering of this block.
  $build['#create_placeholder'] = FALSE;
}


// function visitor_counter_page_attachments(array &$attachments) {
//   $attachments['#attached']['library'][] = 'visitor_counter/visitor_counter';
// }


function visitor_counter_preprocess_page(&$variables) {
   global $base_url;
    $attachments['#attached']['library'][] = 'visitor_counter/visitor_counter';
}
?>





